version: '2'

services:
  flask-restplus-boilerplate:
    image: vccloud/flask-restplus-boilerplate:develop
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    tty: true
    stdin_open: true